version: '3.8'
services:
  server:
    container_name: pyramidion-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - db

  client:
    container_name: pyramidion-client
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  db:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data:/data/db

volumes: 
  data: {}
  server: {}
  client: {}
